name: Tests

on: [push]

jobs:
  run:
    runs-on: ${{ matrix.os }}

    strategy:
      max-parallel: 4
      matrix:
        os: [ubuntu-latest]
        python-version: [2.7, 3.6, 3.7]

    steps:
    - uses: actions/checkout@v1

    - name: Add conda to $PATH
      run: echo ::add-path::$CONDA/condabin

    - name: Update conda
      run: |
        conda update -y -n base conda setuptools
        conda init bash
        conda info -a

    - name: Create the conda environment
      run: conda create -q -y -n voila-tests -c conda-forge python=$PYTHON_VERSION pip jupyter_server==0.1.0 jupyterlab_pygments==0.1.0 pytest==3.10.1 nbconvert=5.6 pytest-cov nodejs flake8 ipywidgets matplotlib xeus-cling
      env:
        PYTHON_VERSION: ${{ matrix.python-version }}
      timeout-minutes: 10

    - name: Install dependencies 
      run: |
        conda activate voila-tests
        whereis python
        python --version
        
        python -m pip install ".[test]"
        cd tests/test_template; pip install .; cd ../../;

    - name: Flake8
      run: |
        conda activate voila-tests
        python -m flake8 voila tests setup.py

    - name: Run tests
      run: |
        conda activate voila-tests
        VOILA_TEST_DEBUG=1 VOILA_TEST_XEUS_CLING=1 py.test tests/ --async-test-timeout=240
        voila --help  # Making sure we can run `voila --help`
